### ISSUE TITLE
.nuspec includes System.Net.Http as a nuget package dependency for .NETFramework4.6.1

### ISSUE THREAD

**Issue by swlasse** [DuendeArchive/IdentityModel#113]
Regarding the nuget package for IdentityModel version 3.6.1: https://www.nuget.org/packages/IdentityModel/3.6.1

I am wondering why `System.Net.Http` is included as a nuget package dependency instead of as a framework assembly dependency for `.NETFramework4.6.1`?

I see that `System.Net.Http` is added as a framework assembly for `.NETFramework4.5.2`, so I am not sure why the same is not done for `.NETFramework4.6.1`?

I might very well be missing something here - I just noticed this, as it causes all of `System.Net.Http`'s dependencies to be included when installing the IdentityModel package into a .NET 4.6.1 project.

**Comment by leastprivilege** [comment]
There is a long list of related issues

https://github.com/IdentityModel/IdentityModel2/issues/31
https://github.com/IdentityModel/IdentityModel2/issues/38
https://github.com/IdentityModel/IdentityModel2/issues/49
https://github.com/IdentityModel/IdentityModel2/issues/70
https://github.com/IdentityModel/IdentityModel2/issues/76

I tried to involve @terrajobst since he is the expert on these things

https://twitter.com/leastprivilege/status/991908438962851840

So the main question is - should a net4xx build target reference the HttpClient nuget package - or the one from the .NET Framework. When you go through the above list, different people have different with one or the other.

**Comment by leastprivilege** [comment]
Fee free to add to the discussion 

https://twitter.com/leastprivilege/status/996686174952546309

**Comment by leastprivilege** [comment]
OK - I pushed an update. If anyone wants to have a look.

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/IdentityModel.csproj

https://www.nuget.org/packages/IdentityModel/3.7.0-preview1

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2018/05/21/the-state-of-httpclient-and-net-multi-targeting/
