### ISSUE TITLE
FileLoadException after upgrading to 3.10.0 on project that uses IdentityServer4

### ISSUE THREAD

**Issue by rverberne** [DuendeArchive/IdentityModel#154]
Hi after upgrading to 3.10.0 we see a System.IO.FileLoadException in a project that uses IdentityServer4 (2.2.0). It's the following line, Client is from IdentityServer4.Models namespace.

`Client client = new Client();`

Dependencies:

`Project A ==> IdentityServer4 (2.2.0) ==> IdentityModel (>= 3.6.1)`
`Project A ==> Project B ==> IdentityModel (3.10.0)`

Exception in dutch (sorry):

`{"Kan bestand of assembly IdentityModel, Version=3.6.1.0, Culture=neutral, PublicKeyToken=null of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)":"IdentityModel, Version=3.6.1.0, Culture=neutral, PublicKeyToken=null"}	System.IO.FileLoadException`

**Comment by leastprivilege** [comment]
IS 2.2 is probably not designed for IdM 3.10 (we needed to do some changes
- including strong naming). For now use the IdM version that IS is compiled
against.

The upcoming IS 2.3 will use IdM 3.10.


-------
Dominick Baier

On 3. October 2018 at 13:07:43, MrGroovy (notifications@github.com) wrote:

Hi after upgrading to 3.10.0 we see a System.IO.FileLoadException in a
project that uses IdentityServer4 (2.2.0). It's the following line, Client
is from IdentityServer4.Models namespace.

Client client = new Client();

Dependencies:

Project A ==> IdentityServer4 (2.2.0) ==> IdentityModel (>= 3.6.1)
Project A ==> Project B ==> IdentityModel (3.10.0)

Exception in dutch (sorry):

{"Kan bestand of assembly IdentityModel, Version=3.6.1.0, Culture=neutral,
PublicKeyToken=null of een van de afhankelijkheden hiervan niet laden. De
manifestdefinitie van de gevonden assembly komt niet overeen met de
assembly-verwijzing. (Uitzondering van HRESULT:
0x80131040)":"IdentityModel, Version=3.6.1.0, Culture=neutral,
PublicKeyToken=null"} System.IO.FileLoadException

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IdentityModel/IdentityModel2/issues/154>, or mute the
thread

**Comment by tomek14** [comment]
I've got the same error when using IdentityServer4.AccessTokenValidation package in my API

**Comment by mattwhetton** [comment]
We just tried upgrading from IdentityModel to 3.10 (from 3.9) and we're also getting issues with IdentityServer4.AccessTokenValidation.

**Comment by leastprivilege** [comment]
Yep - we will release a new wave of identityserver nugets soon.

**Comment by mattwhetton** [comment]
Just to clarify my understanding of this. Am I right in saying that given the introduction of strong naming, minor version changes of IdentityModel will only be compatible with identity server assemblies that they were compiled against?

**Comment by leastprivilege** [comment]
Unless you do a binding redirect. That's how it always worked in .NET (I actually got easier because those redirects are created automatically)

**Comment by marcelstuder** [comment]
I have tried to fix the issue by adding a binding redirect but I could not get it to work - see sample app at: https://github.com/marcelstuder/identitymodelbindingissue 

Automatic binding redirect is enabled and binding redirects get created for all dependencies except the transient IdentityModel.dll required by IdentityModel.AspNetCore.OAuth2Introspection referenced by IdentityServer4.AccessTokenValidation. 

Even manually specifying a binding redirect in a web.config (that gets merged with the automatically generated binding redirects) didn't help.

I am definitely doing something wrong here (binding redirect) or missing some obvious stuff, so if anyone could point me to the right direction I'd really appreciate it.

**Comment by leastprivilege** [comment]
I will update the handlers to use 3.10. I hope this solves all problems.

**Comment by leastprivilege** [comment]
Try 

https://www.nuget.org/packages/IdentityServer4.AccessTokenValidation/2.7.0-preview2

**Comment by marcelstuder** [comment]
2.7.0-preview2 fixed the issue (tried in my sample app: https://github.com/marcelstuder/identitymodelbindingissue)

Thank you @leastprivilege for taking the time to provide a new preview version of the package!
