### ISSUE TITLE
Could not load file or assembly 'IdentityModel

### ISSUE THREAD

**Issue by WahidaSaad** [DuendeArchive/IdentityModel#160]
Could not load file or assembly 'IdentityModel, Version=3.10.1.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'. The system cannot find the file specified.
with .NET CORE 2 application

**Comment by leastprivilege** [comment]
We changed to strong naming in 3.10 - in hindsight should have done a 4.0. But anyways - you need to recompile.

**Comment by valeriob** [comment]
This caused major pain, and took a while to diagnose :(
Can you publish a new version 4 with this change, and mark as obsolete or something the 3.10 one ?
Also all the libraries depending on this one are also all broken, for example IdentityModel.AspNetCore.OAuth2Introspection .
Now we are stuck with 3.9 and a comment on all projects files to not update because of this.

**Comment by leastprivilege** [comment]
Yea - sorry for that. But it is now too late to revert everything back. Lesson learned.
