### ISSUE TITLE
Many locks in AccessTokenDelegatingHandler cause long waits

### ISSUE THREAD

**Issue by adcy** [DuendeArchive/IdentityModel#162]
When i send 100 request simultaneously using AccessTokenDelegatingHandler about half of them ends with Unauthorized error. I investigated that this happen because of lock timeout on AccessToken property of AccessTokenDelegatingHandler. When timeout expired some requests immediately ends, and some executes with Authorization header with empty token.
It is possible get rid of part of this locks? Are they all necessary? For example why property AccessToken is acquire lock?

**Comment by anderaus** [comment]
We've also been hit by this issue.

If multiple requests reach `SendAsync` in `AccessTokenDelegatingHandler` and the token has expired, each request after the first will be locked while the token renews. When the token has renewed, the requests waiting for the lock will **also** try to renew the token. Meanwhile the first request will be locked again because it's trying to access the token later in the `SendAsync` method. Best case scenario is that all requests have to wait for all duplicate renewals of the token before any thread can complete. Worst case, which happens a lot due to the low lock timeout, is that multiple locks will time out resulting in the token being set to `null`.

I hope you can reconsider the PR by @andreycherkashin so others won't have to go through the same problems while waiting for v4.

**Comment by leastprivilege** [comment]
see the PR. I haven't planned any work on the handler since it will be removed.
