### ISSUE TITLE
Discovery Endpoint caching not working when multiple threads consume GetAsync

### ISSUE THREAD

**Issue by flarocca** [DuendeArchive/IdentityModel#372]
Hello!

Related [issue](https://github.com/IdentityModel/IdentityModel/issues/201). This has been closed cause the user didn't provide examples nor deeper explanation, but I ran into the same situation and I was able to isolate the case and understand why.

It happens that the DiscoveryCache is not thread safe, then when the app starts under heavy load, there might be cases where multiple threads would await on GetAsync, resulting on multiple request made. Since it is not thread safe, this causes multiple request to the Discovery Endpoint the first time the document needs to be refreshed or fetched.

After that, it works as expected.

I tested this scenario under 2 different conditions:

IIS 10.0 and .Net Framework 4.8: using Autofac registering the service as Singleton
Docker and .Net Core 3.1: again, registering the service as Singleton
Looking at the code, I see why this is happening:

```
public Task<DiscoveryDocumentResponse> GetAsync()
{
    // If multiple threads get to this point while 
    // the request is being made, a new task per
    // thread will be returned
    if (_nextReload <= DateTime.UtcNow)
    {
        Refresh();
    }

    return _lazyResponse.Value;
}

public void Refresh()
{
    _lazyResponse = new AsyncLazy<DiscoveryDocumentResponse>(GetResponseAsync);
}
```

The current implementation preseted a challenge to me, since it is actually caching the task rather than the document, I first created a wrapper around this cache to cache the result of task. But when I compared that code with the current implementation of the DiscoveryCache, I just realized that it was simpler to create a brand new thread safe caching implementation. 

I feel like I am missing something or I am not understanding how to use the cache properly.

Any suggestions?

I really appreciate your help.
Thank you very much!!

**Comment by flarocca** [comment]
Hello folks!
Any insights on this?

Thank you very much!

**Comment by josephdecock** [comment]
We've decided not to change the discovery cache to prevent multiple threads making disco requests.

The reasons to not do it are that identity model remains simpler, we don't risk deadlocks, and single threaded use doesn't pay the cost of acquiring locks.

The benefit of preventing a few disco requests don't justify the change, especially since concurrency is really hard to get right, and discovery is one of the most used parts of IdentityModel.

Also, I think that if you really want to prevent those disco requests, it should be possible to add a lock around the cache that would do so, in user code. 

That said, we could revisit this issue, but I'd want to make the locking code path totally separate from the existing one, in a new type (a ConcurrentDiscoveryCache).
